version: '2.1'

services:

  dreals-db:
    container_name: dreals-db
    build: ./app/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  dreals-service:
    container_name: dreals-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - FLASK_APP=manage.py
      - DATABASE_URL=postgres://postgres:postgres@dreals-db:5432/dreals_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@dreals-db:5432/dreals_test
    depends_on:
      dreals-db:
        condition: service_healthy
    links:
      - dreals-db